### ISSUE TITLE
500 Error on using it

### ISSUE THREAD

**Issue by B-iggy** [discoursehosting/discourse-suppress-category-from-latest#1]
Good day guys,

first of all thanks a lot for this quick plugin! 💪
Unfortunately, activating it on one of my category makes the main landing page broken.
![image](https://user-images.githubusercontent.com/7815434/71099346-6a081a80-21b3-11ea-8f76-03c26e711df8.png)

![image](https://user-images.githubusercontent.com/7815434/71099238-4218b700-21b3-11ea-95b6-057b916de774.png)

Probably because I am using this page style?
![image](https://user-images.githubusercontent.com/7815434/71099307-5bb9fe80-21b3-11ea-84b3-2e66121bc667.png)

**Comment by communiteq** [comment]
Can you look up the error in /logs and post the backtrace please?

**Comment by B-iggy** [comment]
Hey, sure. Just never did log crawling in Discourse so bare with me.

1st log:
https://gist.github.com/B-iggy/6b1528c7fc35a684c109de2c74291926

2nd log:
https://gist.github.com/B-iggy/155f05c69dca71337e534dfc7720ed32

3rd log:
https://gist.github.com/B-iggy/73aa13d1655fe1f146b9f00e96888456

**Comment by communiteq** [comment]
I pushed a fix, can you rebuild and try again please?

**Comment by B-iggy** [comment]
Awesome mate!
It works!
Thanks for the super fast fix and your time bringing this crucial feature back!
It was a tough 30 days without it 😅
Have nice Holidays! 🎅
