### ISSUE TITLE
Plugin suppress Unread count page

### ISSUE THREAD

**Issue by B-iggy** [discoursehosting/discourse-suppress-category-from-latest#2]
Hi again,
after some rude and childish behavior from one admin guy on the Discourse meta forum, removing my bug tickets all the time, I couldn't stop to investigate and found the issue I think - please watch:

https://streamable.com/it79x

The bug was so difficult to find, because it happened even in safe mode, suggesting that all plugins were turned off. But in fact, your suppress category from latest were still active it seems.

What I'm trying to say: if you have an unread topic in a suppressed category it counts as Unread (as expected). But if you click at Unread (1) you get to an empty page.
Once I remove that check from that category 
![image](https://user-images.githubusercontent.com/7815434/71553915-b6572400-2a17-11ea-99fb-321aced25e8a.png)
the Unread page shows the unread post properly again.

So the suppress plugin here somehow do not show the unread posts on that page. Seems it's suppressed from that page as well!?

**Comment by communiteq** [comment]
Thank you for digging into this. You are indeed correct.
I have pushed a fix, can you please test?

**Comment by B-iggy** [comment]
Awesome! Thank you so much! Works now
