### ISSUE TITLE
Feature request: prevent a subcategory from appearing in the "latest" page of its parent category

### ISSUE THREAD

**Issue by sylque** [discoursehosting/discourse-suppress-category-from-latest#3]
Recently, I decided to move all my categories one level up into two big `French` and `English` categories (localized sub-forums). The issue is that the plugin doesn't suppress the categories in the "latest" page of `French` and `English`.

**Comment by communiteq** [comment]
I pushed a fix. 

Instead of just not suppressing posts in all category views, the code now removes the selected category from the suppress list.

This will suppress posts in subcategories while preventing the issue that suppressed categories appear empty.

**Comment by sylque** [comment]
Amazing, thank you!
